# Generated by Django 4.2.3 on 2023-07-08 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("itemType", models.CharField(max_length=50, verbose_name="itemType")),
                ("title", models.CharField(max_length=50, verbose_name="title")),
                ("price", models.CharField(max_length=50, verbose_name="price")),
                ("rating", models.CharField(max_length=50, verbose_name="rating")),
                ("reviews", models.CharField(max_length=50, verbose_name="reviews")),
                (
                    "imageLink",
                    models.CharField(max_length=150, verbose_name="imageLink"),
                ),
            ],
        ),
    ]
